[tool.black]
line-length = 140
target-version = ["py310"]

[tool.flake8]
max-line-length = 140
extend-select = ["B"]

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true
warn_unused_configs = true
